name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          cache: npm
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: us-east-1
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: |
          S3=1 npm run build
          aws s3 sync dist s3://$S3_BUCKET_NAME
